package model;

import resources.Konstanten;
import utilities.HilfsMethoden;

/**
 *  Diese Klasse ist eine enum Klasse enthielt alle enum Objekte nach ISO 3166-2 Standard und Methoden eines IsoRegion.
 */
public enum IsoRegion {
    IQ_NA, VC_06, CO_TOL, ET_SW, VC_04, PH_NUV, CO_GUV, WS_FA, SK_KI, KR_43, KR_42, KR_41, ET_SN, IQ_NI, UA_23, MV_17,
    CO_GUA, KR_49, KR_48, MX_NAY, UA_26, KR_47, KR_46, MV_13, KR_45, UA_21, ET_SO, KR_44, JP_43, BR_MG, IQ_MA, JP_44,
    CI_LC, JP_45, JP_46, JP_47, CI_LG, LA_KH, BR_MA, JP_40, JP_41, JP_42, PH_NUE, MX_AGU, MV_01, MV_00, IQ_MU, SS_23,
    MV_07, MH_KWA, UA_35, MV_08, MV_03, VU_TOB, UA_30, BR_MS, BR_MT, UA_32, MV_05, SV_MO, UZ_FA, PE_PIU, BY_VI, MU_RP,
    UA_09, PE_LAL, LI_01, PE_LAM, UA_05, UA_07, KR_29, KR_28, KR_27, KR_26, PH_SAR, LA_HO, SV_LI, NL_OV, KZ_ABA, AZ_FUZ,
    KR_31, KR_30, LI_11, UA_18, UA_19, UA_12, UA_14, US_U_A, AF_PKA, ET_OR, BN_TE, TW_CHA, SR_SI, BN_TU, WS_AA, NZ_HKB,
    SR_SA, KY_CB, BF_NOU, RU_BEL, PE_CUS, NL_UT, FR_IDF, LA_OU, AF_PIA, LA_LP, SS_20, SS_21, LA_LM, FR_U_A, SS_22, EG_SUZ,
    IR_16, CI_DN, IR_15, PL_ZP, IR_14, IR_13, MU_VP, IR_19, IR_18, IR_17, EH_U_A, SS_14, SS_15, SS_16, IQ_TS, IR_12, SS_17,
    IR_11, SS_18, IR_10, PE_TUM, SS_19, UZ_AN, GS_U_A, IQ_SD, EG_KFS, CO_CHO, IR_05, IQ_SW, IR_04, MV_20, IR_03, MV_23, IR_02,
    PH_NSA, IR_09, IR_08, UZ_BU, IR_07, KZ_VOS, IR_06, MV_29, MV_28, GQ_LI, IR_01, MV_25, MV_24, IR_00, MV_27, BR_GO, DZ_54,
    SA_10, DZ_55, SK_TA, SA_11, DZ_56, SV_SO, SA_12, PH_BEN, DZ_57, SK_TC, DZ_58, SA_14, SV_SV, SV_SS, KY_GC, NI_CI, MX_JAL,
    DZ_50, SV_SM, DZ_51, DZ_52, NP_P1, NP_P2, SV_SA, CO_CUN, US_DC, TW_TNN, US_DE, TW_TNQ, SO_GE, CI_BS, IR_30, BR_DF, PS_RFH,
    KZ_U_A, NI_CO, KZ_ZHA, NL_ZH, DZ_43, LA_SV, DZ_45, SA_01, SA_02, UZ_QR, AF_HEL, DZ_47, SA_03, SA_04, DZ_48, SA_05, SA_06,
    SA_07, IO_U_A, SA_08, AF_HER, SA_09, SO_GA, LA_SL, DZ_42, IR_27, CI_CM, IR_26, IR_25, UZ_QA, IR_24, BR_ES, IR_29, IR_28,
    MN_1, AE_DU, NL_ZL, IR_23, NI_BO, IR_22, IR_21, IR_20, DZ_32, SV_US, DZ_33, DZ_37, BR_BA, DZ_39, CI_AB, BJ_ZO, US_CA,
    RU_SPE, UZ_NG, PH_SIG, DZ_30, NL_XX, BY_MI, DZ_31, SV_UN, LA_PH, LK_3, LK_2, LK_1, CA_YT, LK_7, LK_6, LK_5, LK_4, PE_LIM,
    NI_AS, NI_AN, DZ_21, DZ_22, DZ_23, DZ_24, SZ_HH, DZ_25, US_CT, DZ_27, VU_PAM, DZ_28, BF_SEN, IQ_WA, EG_FYM, DZ_20, TW_PEN,
    DO_30, SO_HI, MX_ROO, DZ_29, US_CO, BR_CE, UZ_NW, RU_KAM, AE_FU, AZ_XAC, AE_AZ, SI_209, DZ_11, DZ_12, NI_GR, MH_KIL, UA_61,
    DZ_13, IN_BR, DZ_14, GB_U_A, LA_VT, DZ_16, CL_VS, DZ_17, PH_BAS, PH_BAN, AE_AJ, DO_21, DO_20, TR_U_A, DO_25, DO_24, DO_23,
    IN_CH, DO_22, DZ_18, DZ_19, ET_GA, PE_LOR, UA_68, DO_27, UA_63, SD_DE, PH_SCO, UA_65, IN_AP, UA_71, DZ_01, IN_AR, KY_LC,
    PS_NBS, DZ_02, DZ_03, DZ_04, SO_BR, IN_AS, US_AR, DZ_05, DZ_06, NU_U_A, SO_BY, US_AZ, IN_AN, GF_SL, DO_10, AS_WT, BR_AL,
    BR_AM, AZ_XCI, DO_13, BR_AP, SK_NJ, DO_12, LA_XI, BY_MA, DO_11, US_AL, DZ_07, DO_18, BR_AC, DZ_08, EG_BNS, SO_BN, DZ_09,
    DO_16, DO_15, UA_74, LA_XA, US_AK, UA_77, TW_TPE, UZ_JI, VA_U_A, UA_40, CO_LAG, IM_U_A, CO_COR, IN_DL, BF_BAL, MA_HOC,
    TW_TPQ, BF_BAM, ST_P, DO_02, DO_01, CL_TA, UA_46, MX_NLE, DO_05, DO_04, UA_48, UA_43, DO_08, NI_ES, IN_CT, ET_DD, PE_PUN,
    UA_51, BM_U_A, LA_VI, NP_P3, NP_P4, KH_4, NP_P5, KH_3, NP_P6, KH_2, KH_9, NP_P7, KH_8, KH_7, IN_DH, SV_PA, SK_PV, UA_59,
    TW_PIF, UA_53, RU_SMO, US_MA, RU_ORE, GU_U_A, TN_72, CL_RM, US_MI, YE_HD, PH_SOR, UZ_XO, RU_ORL, US_MD, US_ME, NI_LE,
    LT_AL, IN_GJ, CA_SK, BF_SMT, TN_81, TN_82, IN_GA, ET_BE, US_NC, US_ND, BY_HO, TN_83, YE_HU, XK_07, US_NJ, XK_06, XK_05,
    XK_04, US_NE, NI_JI, US_NH, US_MS, XK_03, WS_TU, XK_02, US_MN, XK_01, US_MO, TJ_DU, BY_HR, US_MT, SO_NU, AO_BIE, IS_7,
    IS_8, IS_5, GQ_WN, PK_U_A, IS_6, ET_AA, TN_51, TN_52, ET_AF, TN_53, JM_03, JM_02, JM_01, IN_HP, YE_JA, IN_HR, ET_AM,
    RU_KHA, DK_81, BF_SOM, DK_83, DK_82, RU_KHM, DK_85, DK_84, TW_TTT, PE_UCA, CA_QC, BF_SOR, BF_BLK, US_LA, VU_TAE, TN_61,
    BF_BLG, TW_X_LK, AO_BGO, AO_BGU, PH_BOH, BF_SNG, US_KY, TN_71, IS_3, US_KS, IS_4, IS_1, IS_2, RU_KIR, TN_32, RU_SVE, JP_U_A,
    AF_GHO, CA_NU, US_ID, AZ_XIZ, CA_NT, CA_NS, US_IA, UZ_TO, YE_LA, IN_KL, TW_CYQ, BF_BGR, AF_TAK, CH_ZG, US_HI, AF_GHA, IN_KA,
    CH_ZH, VG_U_A, YE_MA, JM_14, JM_13, JM_12, JM_11, RU_KGD, KZ_ATY, CA_ON, US_IL, IN_JH, RU_KGN, US_IN, IN_JK, JM_09, JM_08,
    JM_07, JM_06, KZ_JET, JM_05, SO_JH, JM_04, PH_WSA, PH_BIL, CA_PE, YE_MU, GY_BA, YE_MR, TN_11, CL_LL, TN_13, SK_ZI, RU_STA,
    WS_PA, NI_MT, CL_LI, NI_MN, CL_LR, TW_TXG, RU_BRY, RU_KDA, GY_CU, US_GA, BN_BE, IN_ML, IN_MN, US_FL, IN_MM, TV_NKF, IN_MP,
    SZ_MA, BN_BM, CA_MB, SZ_LU, SO_MU, AE_U_A, TN_21, CL_ML, TN_23, PH_SLE, BF_SIS, UZ_SU, IN_LA, UZ_SI, KG_GO, CA_NL, RU_KEM,
    IN_LD, GY_DE, KE_300, CL_MA, RU_OMS, SH_AC, TR_38, TR_39, TR_36, TR_37, CO_CES, TR_34, CH_VS, TR_35, TR_32, TR_33, RU_AL, RU_BA,
    TJ_KT, US_TX, IN_OR, RU_KRS, YT_U_A, GY_EB, TR_41, TR_42, CH_VD, TV_NMA, BF_KEN, GM_W, TR_49, TR_47, TR_48, TR_45, TR_46, TR_43,
    DJ_TA, TR_44, FR_NAQ, AZ_KUR, US_VT, SO_WO, LT_KL, IN_MZ, YE_AD, IN_NL, AT_8, YE_AB, AT_9, US_UT, AT_6, PH_BUL, RU_AD, AT_7, AT_4,
    NI_SJ, AT_5, PH_BUK, US_VA, AT_2, TR_52, AT_3, TR_53, TR_50, AT_1, TR_51, AU_TAS, TR_16, TR_17, TR_14, BG_28, RU_TAM, TR_12, US_SC,
    RU_CU, TR_13, US_SD, TR_10, IN_PY, TC_AC, TR_19, RU_DA, CH_SZ, PM_SP, YE_BA, KR_U_A, NI_RI, TR_20, CH_TI, CH_TG, AZ_GOY, TR_27, TR_25,
    TR_26, TR_23, RU_BU, MA_LAA, CH_UR, IN_PB, TR_24, TR_21, TR_22, CV_B, AZ_YE, TR_29, US_TN, AZ_GOR, RU_CE, PS_JEN, PS_JEM, TR_30, TR_31,
    AS_MA, BG_09, TW_X_KM, BG_08, CO_CAL, KZ_AKT, BG_07, BG_06, TJ_GB, NE_4, SO_TO, KZ_AKM, NE_5, NE_6, NE_7, NE_1, NE_2, NE_3, UZ_SA,
    YE_DA, SZ_SH, AF_PAR, BG_12, CV_S, BG_11, BG_10, IN_SK, PG_MBA, BG_16, BG_15, FK_U_A, BG_14, AZ_SM, BG_13, TR_05, MK_002, BG_19, TR_06,
    MK_001, BG_18, TR_03, MK_004, BG_17, TR_04, MK_003, CH_SO, TR_01, MK_006, TR_02, MK_005, MK_008, SO_SA, MK_007, FJ_C, KZ_ALM, AZ_SA, PM_ML,
    FJ_E, US_RI, GB_ENG, VN_CH, TR_09, TR_07, SO_SH, MD_BL, FJ_N, RU_KOS, FJ_R, BG_23, CO_CAS, BG_22, CO_CAQ, BG_20, IN_RJ, BG_27, FJ_W,
    CH_SG, BG_26, CH_SH, KZ_ALA, BG_25, CO_CAU, BG_24, PH_SUN, PH_SUK, EG_C, MH_BIK, PH_BTG, US_OK, SY_U_A, SL_S, DJ_OB, US_OH, SL_N,
    CN_U_A, PH_SUR, IN_UT, CH_OW, PH_BTN, US_NM, LB_AS, CL_CO, LT_KU, SL_W, US_NY, IN_UP, US_NV, RU_KLU, KE_700, LB_BH, MH_WTJ, PE_HUV,
    IN_TG, MH_WTN, US_PA, LB_BA, LT_MR, US_OR, MX_BCN, PE_HUC, IN_TR, WS_VS, MX_BCS, BG_01, SL_E, BG_05, BG_04, IN_TN, BG_03, LB_BI,
    BG_02, PH_MSR, CG_11, AO_LNO, CG_13, CG_12, PH_ZMB, CG_14, AF_ZAB, PH_ILI, AM_VD, IE_RN, BS_IN, PS_GY, CF_UK, UY_LA, OM_SH, GE_IM,
    PH_MSC, HN_SB, GW_TO, TL_OE, RU_CHE, SY_DI, CC_U_A, MX_SIN, RU_CHI, RU_KYA, RU_CHU, IE_TA, BZ_SC, MX_OAX, SN_DK, GE_KA, TL_LA,
    EG_PTS, PH_ILN, CR_L, FR_CVL, BS_HI, KE_900, CR_H, GE_KK, CR_G, CR_C, CR_A, PH_ILS, IE_SO, LA_U_A, CF_SE, MA_TIZ, BA_BIH, KM_A,
    KM_G, PH_MOU, BE_BRU, KM_M, MR_NKC, BS_EG, IT_U_A, CR_P, HN_VA, UY_FS, OM_WU, LV_JEL, BS_EX, GE_MM, AW_U_A, BS_FP, MX_SON, EC_A,
    BO_P, IE_WX, EC_C, BO_O, BO_N, EC_D, CN_63, EC_E, CN_62, BO_L, EC_F, CN_65, IE_WW, EC_G, CN_64, EC_H, MA_TNG, EC_I, BO_H, MA_TNT,
    CF_NM, EC_L, BS_BY, EC_M, AM_TV, NZ_MWT, EC_N, EC_O, KZ_ULY, BO_C, BO_B, EC_P, EC_R, EC_S, BS_CO, EC_T, EC_U, EC_W, PH_EAS, BS_CS,
    GT_AV, EC_X, EC_Y, FI_19, BS_CE, EC_Z, CN_61, UY_DU, FI_16, FI_15, BS_CI, FI_18, BF_MOU, FI_17, BS_CK, FI_12, FI_11, FI_14, BZ_OW,
    FI_13, FI_10, MX_SLP, ZA_U_A, CF_OP, AM_SU, UY_FD, AM_SH, IE_WH, KZ_YUZ, FR_HDF, HN_YO, IE_WD, GT_BV, FI_09, FI_08, FI_05, YE_U_A,
    BO_T, FI_04, BO_S, FI_07, FI_06, CN_45, FI_01, UY_SO, CN_44, FI_03, CF_LB, CN_46, FI_02, CN_41, UY_SJ, CN_43, CN_42, BZ_TOL, SN_KD,
    GT_CQ, MY_03, BS_AK, MY_04, MY_01, MY_02, CO_SUC, TL_VI, MY_07, MY_08, UY_SA, MY_05, MY_06, CF_MB, CN_52, CN_51, CN_54, CN_53, VU_SEE,
    RU_TUL, UY_TT, CF_MP, SY_ID, GE_RL, PH_ISA, PL_DS, CN_50, AU_QLD, BS_BI, RU_LEN, UY_TA, CN_23, CN_22, OM_ZU, CN_21, MA_TAZ, JO_AZ,
    TG_C, GE_SK, GT_ES, GE_SJ, JO_AQ, SY_LA, OM_ZA, TG_K, JO_AM, CN_34, UY_RN, CN_33, GE_SZ, CN_36, CF_KB, CN_35, CN_32, GE_TB, CN_31,
    UY_RV, SN_LG, CF_KG, CN_37, PW_010, UY_RO, MA_TAR, CM_SU, CO_BOY, PF_U_A, KI_G, KI_L, KI_P, CM_SW, CF_HK, GT_HU, GT_GU, CO_BOL,
    BF_ZON, SN_FK, CN_12, TG_S, CN_11, CN_14, CN_13, TG_P, VU_SAM, HK_HK, TG_M, CN_15, MA_CAS, CF_HM, CY_01, BA_SRP, CY_02, CY_05,
    CY_06, SY_DY, CY_03, CF_HS, CY_04, VI_U_A, UY_PA, SY_HI, SY_HM, SY_HL, RU_PER, BF_IOB, SY_HA, UY_MO, GR_A, GT_JU, GR_C, AM_LO,
    GR_B, PH_ZSI, GR_E, GR_D, GR_G, GR_F, GT_IZ, GR_I, GR_H, CU_99, GR_K, GR_J, GR_M, UY_MA, GR_L, AO_CUS, BF_ZOU, AM_KT, MY_14,
    RU_TOM, MY_15, MY_12, MY_13, MY_10, MY_11, MA_TET, MY_16, NA_CA, SD_03, SD_02, SD_05, PL_KP, SD_04, PH_NEC, SD_07, SD_06, SD_09,
    SD_08, RU_YEV, SN_SL, CM_OU, PL_LD, SY_RD, PL_LB, PH_NER, SY_RA, CO_NSA, PH_ALB, AM_ER, SD_01, MH_ARN, PE_CAJ, NZ_XY, TW_KEE, KZ_ZAP,
    SY_QU, NZ_XX, PL_LU, BF_NAO, GA_2, MA_KEN, GA_1, GA_4, GA_3, GA_6, GA_5, GA_8, GA_7, GA_9, PL_MA, PH_AKL, SD_25, MH_NMK, SD_24, MA_KHO,
    SD_26, PA_NB, RU_PRI, CF_BB, NO_XX, PH_ROM, PE_TAC, BZ_BZ, LV_RIX, DK_XX, MH_NMU, NZ_MBH, PL_MZ, SY_TA, CI_YM, SY_SU, SD_13, CM_NO, SN_TC,
    AM_GR, EC_25, EC_26, CM_NW, CI_ZZ, RU_PSK, SN_TH, BZ_CY, CF_BK, MU_AG, MH_AUR, SD_12, SD_11, MR_09, PH_AGS, MR_08, MR_07, NL_FR, IQ_AR,
    TW_KHH, MR_06, MU_GP, MX_TAM, MH_RON, CI_WR, PH_AGN, NL_FL, MX_TAB, SR_BR, RU_YAR, RU_YAN, IQ_AN, AM_AV, NL_GE, PT_03, VE_H, PT_04,
    VE_I, PT_01, VE_J, PT_02, AF_DAY, VE_K, VE_L, VE_M, IQ_BG, VE_N, GT_PE, VE_O, MR_12, HK_NT, MR_11, VE_A, MR_10, PH_RIZ, VE_B, VE_C,
    AM_AR, IQ_BA, VE_D, IQ_BB, VE_E, PS_RBH, VE_F, VE_G, PG_GPK, CM_LT, PT_09, GT_QZ, PT_07, PT_08, PT_05, CF_AC, PT_06, PT_14, RU_LIP,
    HK_U_A, PT_15, PT_12, AZ_SAL, PT_13, RU_TYU, GT_QC, PT_10, PT_11, MR_01, AZ_SAD, PY_ASU, MR_05, MR_04, SN_MT, MR_03, MR_02, NL_DR,
    RU_TVE, AO_CNN, AO_CNO, MG_F, CU_14, CU_15, CU_16, GN_C, MG_T, GN_B, MG_M, PT_18, PT_16, GN_F, PT_17, MH_JAB, GN_K, NA_ER, MG_U,
    CU_10, CU_11, MA_OUA, GN_L, GT_RE, PH_NCO, CU_12, IQ_DI, CU_13, GN_N, PT_20, BF_NAM, MH_JAL, MA_OUJ, IQ_DA, VE_X, GT_SR, VE_Y,
    VE_Z, JO_MN, RU_PNZ, VE_P, VE_R, AF_LOW, VE_S, VE_T, AZ_BAL, VE_U, VE_V, VE_W, JO_MA, PT_30, CI_VB, SR_CR, MG_A, MG_D, CO_ATL,
    GT_SM, GT_SO, CI_SM, BR_TO, LU_W, NA_KH, NA_KA, NA_KE, CI_SV, NA_KW, AO_CCU, NA_KU, LA_BK, LA_CH, AE_UQ, SR_NI, SK_BL, LV_101,
    SN_ZG, CU_03, CU_04, CU_05, CU_06, CU_07, LU_E, CU_08, LU_D, CU_09, IQ_DQ, LU_I, LU_G, LU_L, CU_01, SV_AH, KE_400, SK_BC, BR_RN,
    BR_RO, LV_111, PE_PAS, LV_112, LV_113, BR_RR, CM_EN, RE_SP, BR_RJ, RE_SR, CX_U_A, BR_SC, BR_RS, PY_3, PY_2, MH_ALL, PY_5, SR_PR,
    MH_ALK, PY_4, PY_1, AO_CAB, NL_GR, BR_SP, SR_PM, BR_SE, NA_HA, LA_AT, PH_AUR, PL_WN, MX_CAM, SV_CU, KZ_MAN, CM_ES, PL_WP, BH_14,
    BH_15, RE_SD, BH_16, BH_17, RE_SB, BR_PI, AE_RK, IR_U_A, JP_10, NA_ON, JP_11, JP_12, CM_CE, JP_13, JP_14, JP_15, JP_16, MX_CHH,
    JP_17, BR_PA, BR_PB, NA_OD, TW_TAO, BR_PE, MU_PA, PH_APA, BZ_CZL, PL_OP, NA_OH, ET_XSD, MH_ENI, PL_PK, JP_07, BR_PR, JP_08, NA_OS,
    JP_09, NA_OT, PL_PD, NA_OW, MX_CHP, PG_CPM, JP_01, JP_02, JP_03, PY_7, JP_04, PY_6, BQ_U_A, JP_05, PH_ANT, PY_9, JP_06, PY_8, GT_ZA,
    PL_PM, GQ_AN, PG_CPK, NL_NH, CO_SAP, CO_SAN, NL_NB, KR_11, JP_32, CI_MG, JP_33, JP_34, JP_35, JP_36, JP_37, JP_38, JP_39, CM_AD, SR_MA,
    JP_30, GQ_BN, JP_31, AZ_BIL, JP_29, HM_U_A, GF_CY, JP_21, JP_22, JP_23, JP_24, AE_SH, JP_25, JP_26, JP_27, JP_28, GQ_CS, JP_20,
    PL_SK, NL_LI, ET_TI, PL_SL, JP_18, JP_19, AZ_SKR, PG_WBK, LV_054, TH_91, TH_90, MW_MZ, LV_056, NG_AD, TH_92, TH_95, LV_058,
    LV_059, TH_94, PH_DAS, TH_96, IL_D, NG_AB, SI_090, NZ_NSN, PH_DAO, PG_JI, LV_050, MW_NB, TD_EE, AD_08, PE_ANC, BF_LOR, IL_M,
    AD_04, MW_NK, RS_00, PH_DAV, AO_MOX, RS_01, ZA_GT, MW_NI, SI_085, MX_GUA, TD_EO, MA_BEM, NG_AK, MW_NS, IL_Z, LY_BU, PG_NPP,
    BI_GI, FR_BRE, ID_ST, ID_SS, CK_U_A, ID_SU, LV_067, ZW_HA, KW_FA, MW_MG, AF_NIM, MW_MC, LV_062, SI_094, MT_62, AZ_MAS, SI_092,
    PS_GZA, GH_AA, MW_MH, PE_AMA, LV_077, TH_71, KZ_KUS, TH_70, TH_72, RS_16, TH_74, RS_13, TH_77, RS_14, TH_76, RS_19, PG_NSB, TD_CB,
    RS_17, GH_AH, RS_18, LV_073, SI_061, MW_LK, SI_060, MW_LI, RS_22, RS_23, RS_20, MX_GRO, MX_TLA, MF_U_A, GH_BO, RU_ULY, LV_087,
    TH_80, LV_088, TH_81, TH_84, TH_83, RS_04, TH_86, EG_U_A, LY_BA, RS_05, NZ_NTL, TH_85, RS_02, RS_03, RS_08, SI_080, RS_09, RS_06,
    SB_GU, RS_07, SI_073, SI_070, BE_WBR, CO_RIS, RS_11, RS_12, CO_NAR, RS_10, MW_KR, SI_078, MW_KS, EG_MNF, MT_44, NG_EK, GH_CP,
    NG_EN, LV_011, TH_51, BI_BM, LY_GT, TH_50, TH_53, NG_ED, TH_52, TH_55, TH_54, TH_57, TH_56, TH_58, SI_040, SI_043, PE_ARE, SI_048,
    LV_007, GD_PA, MW_RU, ID_YO, LV_022, KW_JA, TH_60, HU_BK, MX_COL, LV_026, ZA_MP, MX_COA, TH_64, KZ_PAV, TH_63, NG_DE, HU_BE, TH_65,
    TH_67, TD_BA, HU_BA, SI_050, NZ_WGN, CY_XX, TD_BG, LV_016, SI_058, SI_059, TD_BO, PE_APU, ZW_MI, GH_EP, LV_033, ZA_NL, ZW_MC, ZW_ME,
    TH_31, ZA_NP, TH_30, ZW_MA, TH_32, PG_HE, TH_35, TH_34, HU_BZ, SI_022, TF_U_A, LY_DR, SI_025, NG_CR, ER_SK, HU_BU, ZA_NC, SI_028,
    LV_041, LV_042, SB_CE, SB_CH, NG_BE, KW_HA, KZ_KZY, LU_RM, TH_40, TH_42, NG_BA, TH_41, TH_46, TH_45, TH_48, TH_47, NG_BY, ZW_MW,
    ZA_NW, ZW_MS, ZW_MV, HU_CS, ZW_MN, NG_BO, LU_RD, SI_039, DE_ST, AO_ZAI, RO_CJ, SI_009, RO_CL, TD_MA, TD_MC, DE_SN, NG_IM, TD_ME,
    CO_ARA, DE_SL, AU_WA, AZ_ZAN, DE_SH, FM_YAP, NO_21, NO_22, AZ_ZAQ, TD_MO, NO_15, KW_MU, BF_HOU, NO_18, LY_KF, PK_GB, GA_U_A, SI_001,
    RO_CS, RO_CT, SI_008, SI_006, RO_BH, TD_ND, RO_BN, PS_KYS, MH_EBO, RO_BC, DE_TH, NO_11, PH_00, HU_FE, NO_03, RO_BZ, NZ_WKO, SI_011,
    SI_012, RO_BR, SI_013, SI_019, SB_ML, RO_BV, SB_MK, BE_WHT, BW_ST, HU_GS, HR_08, MM_13, HR_07, MM_12, NG_GO, MM_15, HR_09, MM_14,
    MM_17, TD_KA, HR_03, MM_16, HR_06, HR_05, HR_02, HR_01, BW_SP, BW_SO, FM_PNI, KW_KU, AU_XX, HR_19, RO_DJ, MM_02, FR_GES, HR_18,
    MM_01, MM_04, DE_RP, MM_03, MM_06, PK_IS, LY_JU, MW_SA, HR_14, MM_05, HR_17, TD_LC, HR_16, MM_07, HR_11, RO_DB, HR_13, HR_12,
    MA_FES, NG_FC, LY_JA, HU_HE, TD_LO, HU_HB, TW_NAN, TD_LR, LY_JG, HU_GY, MM_11, SE_S, SE_T, LV_097, SE_Q, LV_099, AU_SA, SE_M,
    SE_N, ZW_BU, HR_21, PK_BA, SE_Y, EG_MT, SE_Z, LV_091, SE_W, MW_ZO, SE_X, SE_U, HR_20, LV_094, LR_CM, CO_AMA, DE_NW, BL_U_A, MA_BAH,
    MA_FIG, BB_02, BB_01, ZA_EC, BB_08, EG_LX, HU_JN, NO_50, RS_24, SB_IS, NO_54, CO_ANT, NO_46, SE_C, EG_MN, ML_4, SE_D, ML_5, ML_6,
    ML_7, ML_1, ML_2, ML_3, SE_K, PH_LUN, SE_I, MQ_U_A, NC_U_A, SE_G, ML_8, SE_H, IL_HA, SE_E, SE_F, RO_AG, GL_AV, NG_KT, PE_AYA, AQ_U_A,
    NG_KN, NG_KO, UG_N, FM_TRK, LR_BG, RO_AB, PG_WHM, NO_42, NG_KE, UG_W, EG_KN, LY_MQ, LV_VEN, HU_KE, NO_38, LY_MI, NG_LA, LY_MJ, IT_34,
    TD_GR, IT_36, RO_AR, NG_KW, IT_32, LY_MB, PG_SAN, DE_NI, EG_JS, LY_NL, GW_BL, NG_JI, GH_NP, NO_30, LY_NQ, NO_34, RU_MAG, UG_C, NG_KD,
    TD_HL, ZA_FS, IL_JM, DE_MV, IT_23, IT_25, UG_E, GW_BA, IT_21, MA_JDI, OM_DA, MH_MIL, EG_IS, LY_SR, PE_SAM, AU_NT, SB_WE, NG_RI, GW_BS,
    JO_U_A, HN_AT, IT_55, LY_SB, IT_57, IT_52, LY_SH, AU_ACT, HN_CH, MX_PUE, OM_BU, BW_NE, HU_NO, NG_PL, RU_MOS, AO_HUA, BW_NW, LY_TB,
    IT_45, AO_HUI, SC_20, PK_PB, OM_BA, TD_WF, IT_42, RU_MOW, SC_21, BW_KL, IE_CE, RO_MS, BT_42, IT_72, BT_41, TD_SI, NG_OS, NG_ON,
    RO_MM, IE_CN, BW_KG, IE_CW, HN_CR, KE_110, IT_77, HN_CM, HN_CL, IT_78, NG_OY, FR_PAC, TD_TA, BW_KW, HN_CP, EG_GZ, ER_GB, IT_75,
    LR_GB, PH_MDC, TD_TI, BW_LO, LR_GK, UA_U_A, HU_PS, LR_GG, CO_VAU, NG_NI, EG_GH, NG_OG, PH_MDR, PH_MDS, RO_MH, PH_MDN, DM_10, HU_PE,
    IT_67, IT_62, CO_VAC, IT_65, PW_004, RO_GR, BT_24, MH_MEJ, CO_QUI, LR_LO, RO_GJ, BE_WLG, PK_JK, RO_GL, RW_02, SB_RB, RW_03, RW_04,
    RW_05, RO_HD, RW_01, GW_GA, DM_02, HN_EP, AU_VIC, DE_HH, IT_82, BT_31, PK_KP, DE_HE, GH_UE, BT_33, BT_32, LR_MG, MX_HID, BT_34,
    DE_HB, GH_TV, ER_DK, EG_DK, HN_GD, IE_DL, LR_MO, BS_WG, IT_88, HN_FM, BW_JW, TD_SA, BE_WLX, BW_GH, SC_15, BS_SO, SC_14, TD_OD, RO_IS,
    FR_PDL, HU_SZ, BS_SS, SC_18, PG_SHM, BS_SE, GH_UW, TT_TOB, RO_IL, NG_SO, BW_GA, PH_MAD, SB_TE, HU_SO, HU_SN, HU_SK, VN_SCC,
    BE_WNA, AO_MAL, PG_WPD, PH_MAS, NG_TA, LY_WA, RO_HR, BT_11, HN_IN, BT_13, RO_B, BT_12, LY_WD, HN_IB, EG_BH, HU_TO, RO_IF, BT_15,
    GH_WP, NG_ZA, CG_9, CG_8, CG_7, HU_VA, CG_5, GL_KU, AG_04, CG_2, AG_03, DE_BY, AG_05, DE_BW, RO_SV, UY_CA, AF_NAN, DE_BR, EG_BA,
    RO_TL, RO_TM, MA_ESI, BS_RC, MH_MAJ, MH_MAL, DE_BE, IL_TA, GE_AJ, GE_AB, BS_RI, UY_CO, RO_SJ, UY_CL, RO_SM, BS_SA, AO_LUA, RO_SB,
    GP_U_A, BW_FR, MA_ERR, HU_VE, LR_NI, BW_CH, CO_VID, IE_KK, HN_LP, BW_CE, HN_LE, LR_MY, RO_VL, TL_CO, FR_COR, IE_KY, SX_U_A, GL_NE,
    IE_LD, KE_500, SG_05, LV_002, PE_JUN, BD_6, BD_5, BD_4, RO_TR, BD_3, RU_MUR, BD_2, BD_1, AG_10, AO_LSU, MH_UTI, TL_DI, IE_KE, UY_AR,
    PH_QUE, SG_04, RU_VGG, SG_03, SG_02, SG_01, IE_MO, BS_MG, HU_ZA, ZM_04, ZM_05, ZM_06, ZM_07, ZM_08, ZM_09, RO_OT, PH_DVO, RO_PH, TT_TUP,
    ZM_01, ZM_02, ZM_03, TL_AT, NZ_AUK, PK_SD, AR_L, RO_NT, AR_M, AR_J, AR_K, AR_H, MX_DIF, TL_BA, GL_QA, AR_F, BS_NO, AR_G, IE_LK, AR_D,
    AR_E, AR_B, AR_C, PA_10, AR_A, HN_OL, IE_LS, ZM_10, HN_OC, TL_BO, GL_QK, BS_NP, BS_NS, IE_MH, FM_KSA, LR_RI, IE_OY, CF_VR, AR_Z, AO_UIG,
    AR_X, OM_MU, AR_Y, AR_V, AR_W, AR_T, AR_U, TM_D, AR_R, AR_S, TM_B, AR_P, AZ_AGC, TM_A, AR_Q, AR_N, AZ_AGA, GL_SE, BS_LI, PH_ZAS, GE_GU,
    PH_ZAN, TT_CTT, OM_MA, AZ_AGM, AZ_AGS, ZA_WC, LR_SI, KH_12, KH_11, TC_GT, KH_10, CH_NE, KH_16, BF_OUD, KH_15, BJ_CO, KH_13, CL_BI,
    TJ_SU, KH_19, RU_IN, KH_18, KH_17, IN_WB, CA_BC, CL_AP, GY_MA, CL_AR, BF_KMP, CL_AN, ST_03, PH_TAR, CL_AT, FR_ARA, CZ_ZL, TM_M, MH_UJA,
    TM_L, SH_TA, ST_01, VU_MAP, BJ_DO, MD_FR, TM_S, ES_VC, AZ_NX, CH_NW, KZ_BAY, LT_SA, NZ_OTA, CO_MAG, PE_MDD, BJ_AQ, LT_PN, BJ_AK, MD_CT,
    AF_FYB, PH_CAG, BJ_AL, MD_CU, PH_CAS, RU_KR, PH_CAT, RU_KO, MD_CL, PH_CAP, EG_WAD, PH_CAM, PH_CAN, MD_CH, VN_NW, AF_KAP, CZ_VY, BF_KOS,
    BF_KOT, CO_HUI, BF_KOP, PH_CAV, PG_MPL, PG_MPM, HT_AR, SI_188, SI_189, BJ_BO, GY_PT, AF_KAB, GB_NIR, PH_TAW, PG_MRL, KZ_SEV, CL_AI,
    HT_CE, TJ_RR, CA_AB, AF_KAN, CH_LU, RU_KL, RU_KK, GY_PM, RU_KB, MX_YUC, RU_VOR, VN_NC, MO_CAR, VN_NE, RU_IVA, RU_KC, RU_IRK, NZ_GIS,
    PY_10, AZ_LA, TR_79, TR_76, PY_12, TR_77, NZ_CAN, PY_11, PY_14, RU_VLA, PY_13, MN_069, PY_16, PY_15, MN_065, PY_19, MN_067, SI_160,
    MN_061, RU_VLG, MN_063, EG_AST, MA_AGD, MD_IL, LT_VL, ES_RI, FR_NOR, BF_GAN, TR_80, GI_U_A, NZ_TAS, MN_071, MN_073, CH_JU, SI_174,
    PS_BTH, TW_YUN, CZ_US, TW_HSZ, TR_58, TR_59, ES_PV, TR_56, TR_57, VN_RRD, TR_54, US_WI, TR_55, MN_046, MN_047, SH_SH, CD_TS, MN_043,
    CD_TU, CD_SU, LT_TA, MN_041, SI_142, CH_GR, TR_63, TR_64, TR_61, CD_TA, TR_60, LT_TE, US_WA, MD_GA, LT_UT, MA_NAD, TR_67, LB_JL, MN_U_A,
    TR_68, TR_65, MN_057, MN_059, EG_ASN, MN_055, GY_UD, LB_JA, MN_051, CZ_ST, HT_GA, US_WV, SI_153, US_WY, TR_74, TR_72, TR_73, TR_71, MX_ZAC,
    AL_12, AL_11, AL_10, EE_7B, EE_86, CZ_PR, PH_PAN, PH_PAM, EE_82, ES_NC, EE_84, SC_U_A, BF_GNA, UM_67, WF_U_A, CZ_PL, GY_UT, SI_126, AZ_GA,
    AL_02, AL_01, ES_ML, PG_EHG, MX_DUR, MN_039, CD_SK, MN_035, CH_GE, AL_08, AL_07, AL_06, CH_GL, EE_67, AL_05, EE_74, UM_71, ES_MC, CH_FR,
    EE_70, SI_130, TC_NC, ES_MD, UM_79, CD_SA, DJ_DJ, DJ_DI, PA_3, PA_2, PA_5, RU_TA, PA_4, MX_MEX, PA_1, AF_ORU, RU_ALT, EE_57, PA_7, PA_6,
    EE_59, PA_9, PA_8, LB_NA, EE_65, BF_GOU, TW_HUA, SI_102, SI_100, AI_U_A, SI_106, SI_104, RU_SA, PE_ICA, YE_SD, CZ_PA, RU_SE, LV_DGV,
    YE_SN, DJ_AS, RU_AMU, DJ_AR, TC_PR, YE_SH, AZ_HAC, TC_PN, EE_51, QA_KH, SI_114, RU_NGR, SI_112, RU_ROS, CZ_OL, LC_02, NZ_TKI, YE_TA,
    EE_39, KN_U_A, AF_KHO, CD_NK, EE_37, CH_BE, CD_MO, CH_AI, CH_AG, EE_44, PG_EBR, QA_DA, CH_AR, FO_U_A, SE_AB, SE_AC, BE_VAN, CZ_LI,
    EG_ALX, LC_11, VN_SW, BF_TAP, CZ_MO, BE_VBR, CO_MET, MD_RS, CD_NU, RU_MO, CH_BL, CH_BS, ES_IB, AZ_BA, RU_NEN, RU_ME, ID_BB, IE_C,
    ID_BE, MP_U_A, IE_D, MA_RBA, CZ_KA, IE_G, ID_BA, HT_NO, CD_KN, CZ_JM, CD_KO, ID_BT, HT_NE, HT_ND, CD_KU, TC_MC, PE_MOQ, VN_SE, CD_KW,
    CZ_JC, CD_MA, ID_AC, HT_OU, CD_MN, CD_LO, CZ_KR, AF_KDZ, CD_LU, ES_GA, MX_MIC, SE_BD, MZ_MPM, PH_CEB, KG_C, KG_J, KG_N, MZ_A,
    PH_LAG, NR_14, KG_O, MZ_G, PH_LAS, KG_T, MZ_I, MZ_B, PH_LAN, KG_Y, ES_EX, MZ_N, ME_20, AO_NAM, CD_IT, RU_RYA, MZ_P, MZ_Q, ME_21,
    TV_FUN, MZ_L, AF_BAL, TC_WC, TW_MIA, AF_BAM, CD_KC, CD_KE, PR_U_A, NZ_WTC, MX_U_A, QA_RA, CD_KI, MX_MOR, ZM_U_A, KG_B, PH_COM,
    BF_COM, MH_LIK, CO_PUT, EG_SIN, TZ_18, TZ_19, GB_WLS, TZ_23, ES_CT, TZ_24, TZ_21, EG_SHR, TZ_22, GB_SCT, TZ_25, MD_SV, TZ_26,
    ME_03, BE_VOV, PG_EPW, TZ_20, MD_SN, ES_CE, ES_CB, MX_QUE, MZ_S, MZ_T, ES_CM, ES_CL, AF_JOW, ES_CN, QA_SH, CD_HK, ME_16, CD_HL,
    ME_19, IQ_U_A, ME_12, HT_SD, CD_HU, HT_SE, PG_NCD, TO_01, TO_03, TO_02, MX_VER, MA_U_A, NZ_BOP, TO_05, TO_04, MA_IFR, ES_AS,
    TZ_01, ES_AR, TZ_02, TZ_05, TZ_03, TC_SL, TZ_04, MW_BL, CD_EQ, TC_SC, RU_UD, BF_PAS, RU_AST, EG_SHG, TZ_09, ID_GO, TZ_07,
    RU_TY, TZ_08, ES_AN, FR_BFC, PW_350, TZ_12, TZ_13, TZ_16, TZ_17, TZ_14, MV_MLE, SM_06, KE_200, SM_03, ID_JK, RU_NIZ, ID_JI,
    GD_AN, ID_JT, BE_VLI, UM_84, UM_81, UM_86, UM_89, ID_KB, FR_OCC, CO_DC, NF_U_A, UM_95, PH_GUI, ID_JB, RU_ARK, BI_RY, HK_KLN,
    BI_RT, ID_JA, RU_SAM, RU_SAK, TH_10, TH_13, TH_12, RU_SAR, TH_16, BF_PON, TH_19, ID_MA, BE_VWV, CD_BU, NZ_STL, BR_U_A, ID_KI,
    AZ_QAB, ID_KT, TH_20, ID_KS, AF_FRA, TH_22, ID_KU, TH_21, TH_24, TH_23, TH_26, TH_25, PG_NIK, TH_27, MA_MAR, ID_LA, MW_CT,
    MH_LAE, BI_MA, RU_NVS, ID_NT, MW_DE, KP_04, KP_05, KP_02, KP_03, KP_01, AU_NSW, KP_08, KP_09, KP_06, KP_07, ID_MU, BI_NG,
    BF_YAT, KP_13, MW_CK, ID_NB, KP_10, ID_PP, ID_PS, GD_GE, ID_PT, TW_ILA, BI_KI, KW_AH, PH_LEY, KE_600, LS_C, LS_A, LS_G,
    MA_MEK, LS_F, LS_E, ID_PA, LS_K, LS_J, PH_PLW, ID_PB, LS_H, MT_26, PG_ESW, BE_XX, MT_25, GG_U_A, AF_BDS, CW_U_A, TD_U_A,
    BF_TUI, QA_WA, ID_SB, ID_SA, ID_SN, AF_BDG, ID_SG, MT_13, VN_U_A, MS_SG, JE_U_A, MC_U_A, KZ_KAR, CR_SJ, MS_SP, MT_05,
    MO_SEE, MT_01, ID_RI, BY_BR, PH_SLU, CA_NB, NE_8, BF_KAD;


    /**
     * Findet die entsprechende IsoRegion vom enum List fuer die vorgegebene String
     * @Vorbedingung ein String muss schon gegeben werden
     * @Nachbedingung IsoRegion vom enum List wird zurueckgegeben
     * @param value String vom Einlesen
     * @return AirportType vom enum List
     */
    public static IsoRegion IsoRegionFromCode(String value)
    {
        for (IsoRegion isoRegion : IsoRegion.values())
        {
            if (HilfsMethoden.replaceUnderscore(isoRegion.toString()).equalsIgnoreCase(value) )
            {
                return isoRegion;
            }
        }
        //falls String mit keinem Objekt vom enum List passt
        throw new IllegalArgumentException(Konstanten.INVALID_ISOREGION + value);
    }

    /**
     * Gibt der IsoRegion vom enum List formatiert als String zurueck.
     * @Vorbedingung IsoRegion vom enum List muss initialisiert sein.
     * @Nachbedingung isoRegion vom enum List wird formatiert als String zurueckgegeben.
     * @return IsoRegion vom enum List formatiert als String
     */
    public String toString() {
        return name();
    }
}
